language: php
php:
   - '5.6'
   - '7.0'
   - '7.1'
   - '7.2'
   - '7.3'
install:
   - composer install -vvv
   - cp .env.example ./vendor/laravel/laravel/.env
script:
   - ./vendor/bin/phpcs
   - ./vendor/bin/phpunit